name: measures

on: workflow_dispatch

env:
  GBXML: master
  COMMON: v0.8.0
  SYSTEMS: main

jobs:
  update:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      # TODO edit sparse-checkout after non-gbxml measures are removed from repo
      - name: sparse checkout NREL/gbxml-to-openstudio
        uses: actions/checkout@v3
        with:
          repository: NREL/gbxml-to-openstudio
          ref: ${{ env.GBXML }}
          path: gbxml
          sparse-checkout: |
            measures/import_gbxml
            measures/advanced_import_gbxml
            measures/gbxml_hvac_import
            measures/gbxml_to_openstudio_cleanup

      - name: copy files from NREL/gbxml-to-openstudio
        shell: bash
        run: cp -r gbxml/measures measures
    
      - name: sparse checkout NREL/openstudio-common-measures-gem
        uses: actions/checkout@v3
        with:
          repository: NREL/openstudio-common-measures-gem
          ref: ${{ env.COMMON }}
          path: common
          sparse-checkout: |
            lib/measures/ChangeBuildingLocation
            lib/measures/openstudio_results
       
      - name: copy files from NREL/openstudio-common-measures-gem
        shell: bash
        run: cp -r common/lib/measures/* measures

      - name: sparse checkout NREL/SystemsAnalysisReports
        uses: actions/checkout@v3
        with:
          repository: NREL/SystemsAnalysisReports
          ref: ${{ env.SYSTEMS }}
          path: systems
          sparse-checkout: measure/systems_analysis_report_generator
          
      - name: copy files from NREL/SystemsAnalysisReports
        shell: bash
        run: cp -r systems/measure/* measures
 
      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: measures
          path: measures
          
  pull-request:
    needs: update
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
      
      - name: list
        run: |
          ls measures/   

      - name: pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update measures
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[action] update measures'
          branch: action/update-measures
          base: main  
